### ISSUE TITLE
Debt Seniority for Total Return Swap

### ISSUE THREAD

**Issue by TonyBirrell** [ANNA-DSB/Product-Definitions#100]
Total Return Swap Debt Seniority – This attribute is only relevant where there is an ISIN as an underlier not relevant when there is an Index as an underlier. The DSB will reject a request with an index underlier and a Debt seniority other than ‘n/a’ and reject a request with an ISIN underlier and a debt seniority of ‘n/a’

**Comment by kristinehui** [comment]
Fixed.
