### ISSUE TITLE
Date validation 

### ISSUE THREAD

**Issue by tongc** [ANNA-DSB/Product-Definitions#103]
all Date fields have this regular expression defined in the schema.
^[0-9]{4}-[0-9]{2}-[0-9]{2}$
However, there is no month greater than 12. And in fact if we send month 13 we will get error message from ANNA DSB. 
So why don't we set this regular expression to be more accurate - reflect ANNA DSB server side checking rules?

**Comment by TonyBirrell** [comment]
Hi, please contact the secretariat@ANNA-DSB.com with this query
