### ISSUE TITLE
Credit.Swap.Index: UnderlyingInstrumentIndex enmerations contain Series

### ISSUE THREAD

**Issue by VatanoS** [ANNA-DSB/Product-Definitions#106]
In Credit.Swap.Index JSON, UnderlyingInstrumentIndex enmerations contain Series number. e.g. "ITRAXX EUROPE SERIES 26"

In the Annex-Credit PDF file, example given is "iTraxxEurope"

Should UnderlyingInstrumentIndex only contain index name? Given Series is capatured in UnderlyingCreditIndexSeries

**Comment by PeterDavisLGIM** [comment]
I have the same question. Why do the credit index enumerations include the series number when the series is provided as a separate data item.

**Comment by TonyBirrell** [comment]
Please forward your query directly to the secretariat@ANNA-DSB.com
