### ISSUE TITLE
Final list of templates withheld from Production on October 2nd

### ISSUE THREAD

**Issue by TonyBirrell** [ANNA-DSB/Product-Definitions#108]

**Comment by TonyBirrell** [comment]
**Commodities**
Commodities.Swap.Basis_Swap.InstRefDataReporting.V1.json
Commodities.Forward.Multi_Exotic_Forward.InstRefDataReporting.V1.json
Commodities.Option.Multi_Exotic_Option.InstRefDataReporting.V1.json
Commodities.Swap.Multi_Exotic_Swap.InstRefDataReporting.V1.json

**Credit**
Credit.Swap.Index_Tranche.InstRefDataReporting.V1.json
Credit.Swap.Index.InstRefDataReporting.V1.json
Credit.Swap.Total_Return_Swap.InstRefDataReporting.V1.json

**Equity**
Equity.Option.Single_Index.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Dividend_Single_Index.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Variance_Single_Index.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Volatility_Single_Index.InstRefDataReporting.V1.json
Equity.Swap.Price_Return_Basic_Performance_Single_Index.InstRefDataReporting.V1.json
Equity.Swap.Price_Return_Basic_Performance_Single_Index_CFD.InstRefDataReporting.V1.json
Equity.Forward.Price_Return_Basic_Performance_Single_Index.InstRefDataReporting.V1.json
Equity.Forward.Price_Return_Basic_Performance_Single_Index_CFD.InstRefDataReporting.V1.json
Equity.Option.Basket.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Dividend_Basket.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Variance_Basket.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Volatility_Basket.InstRefDataReporting.V1.json
Equity.Swap.Price_Return_Basic_Performance_Basket.InstRefDataReporting.V1.json
Equity.Swap.Price_Return_Basic_Performance_Basket_CFD.InstRefDataReporting.V1.json
Equity.Forward.Price_Return_Basic_Performance_Basket.InstRefDataReporting.V1.json
Equity.Forward.Price_Return_Basic_Performance_Basket_CFD.InstRefDataReporting.V1.json
Equity.Swap.Portfolio_Swap.InstRefDataReporting.V1.json

**Comment by kristinehui** [comment]
Fixed.
