### ISSUE TITLE
Final list of templates to be released into Production on October 2nd

### ISSUE THREAD

**Issue by TonyBirrell** [ANNA-DSB/Product-Definitions#109]
•	Commodities: 
Commodities.Forward.Forward.InstRefDataReporting.V1.json
Commodities.Option.Option.InstRefDataReporting.V1.json
Commodities.Option.Swaption.InstRefDataReporting.V1.json
Commodities.Swap.Swap.InstRefDataReporting.V1.json

•	Credit:
Credit.Option.Index_Swaption.InstRefDataReporting.V1.json
Credit.Option.Single_Name_Swaption.InstRefDataReporting.V1.json
Credit.Swap.ABS.InstRefDataReporting.V1.json
Credit.Swap.Corporate.InstRefDataReporting.V1.json
Credit.Swap.Municipal.InstRefDataReporting.V1.json
Credit.Swap.Sovereign.InstRefDataReporting.V1.json

•	Equities:
Equity.Forward.Price_Return_Basic_Performance_Single_Name.InstRefDataReporting.V1.json
Equity.Forward.Price_Return_Basic_Performance_Single_Name_CFD.InstRefDataReporting.V1.json
Equity.Option.Single_Name.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Dividend_Single_Name.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Variance_Single_Name.InstRefDataReporting.V1.json
Equity.Swap.Parameter_Return_Volatility_Single_Name.InstRefDataReporting.V1.json
Equity.Swap.Price_Return_Basic_Performance_Single_Name.InstRefDataReporting.V1.json
Equity.Swap.Price_Return_Basic_Performance_Single_Name_CFD.InstRefDataReporting.V1.json

•	FX:
Foreign_Exchange.Forward.Contract_For_Difference.InstRefDataReporting.V1.json
Foreign_Exchange.Forward.Forward.InstRefDataReporting.V1.json
Foreign_Exchange.Forward.NDF.InstRefDataReporting.V1.json
Foreign_Exchange.Forward.Rolling_Spot.InstRefDataReporting.V1.json
Foreign_Exchange.Forward.Spreadbet.InstRefDataReporting.V1.json
Foreign_Exchange.Forward.Vol_Var.InstRefDataReporting.V1.json
Foreign_Exchange.Option.Barrier_Option.InstRefDataReporting.V1.json
Foreign_Exchange.Option.Digital_Option.InstRefDataReporting.V1.json
Foreign_Exchange.Option.Forward_Vol_Agreement.InstRefDataReporting.V1.json
Foreign_Exchange.Option.NDO.InstRefDataReporting.V1.json
Foreign_Exchange.Option.Target_Option.InstRefDataReporting.V1.json
Foreign_Exchange.Option.Vanilla_Option.InstRefDataReporting.V1.json

•	Rates:
Rates.Forward.FRA_Index.InstRefDataReporting.V1.json
Rates.Forward.FRA_Other.InstRefDataReporting.V1.json
Rates.Option.CapFloor.InstRefDataReporting.V1.json
Rates.Option.Debt_Option.InstRefDataReporting.V1.json
Rates.Option.Swaption.InstRefDataReporting.V1.json
Rates.Swap.Basis.InstRefDataReporting.V1.json
Rates.Swap.Basis_OIS.InstRefDataReporting.V1.json
Rates.Swap.Cross_Currency_Basis.InstRefDataReporting.V1.json
Rates.Swap.Cross_Currency_Fixed_Fixed.InstRefDataReporting.V1.json
Rates.Swap.Cross_Currency_Fixed_Float.InstRefDataReporting.V1.json
Rates.Swap.Cross_Currency_Fixed_Float_NDS.InstRefDataReporting.V1.json
Rates.Swap.Cross_Currency_Zero_Coupon.InstRefDataReporting.V1.json
Rates.Swap.Fixed_Fixed.InstRefDataReporting.V1.json
Rates.Swap.Fixed_Float.InstRefDataReporting.V1.json
Rates.Swap.Fixed_Float_OIS.InstRefDataReporting.V1.json
Rates.Swap.Fixed_Float_Zero_Coupon.InstRefDataReporting.V1.json
Rates.Swap.Inflation_Basis_Zero_Coupon.InstRefDataReporting.V1.json
Rates.Swap.Inflation_Fixed_Float_YoY.InstRefDataReporting.V1.json
Rates.Swap.Inflation_Swap.InstRefDataReporting.V1.json

**Comment by kristinehui** [comment]
Fixed
