### ISSUE TITLE
Commodity Basis Swap issue

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#110]
There is a bug in Commodity Basis Swap whereby when it is created, Additional Sub Product and Other Additional Sub Product are swapped. E.g. a user input of Leg1[ARGI, GROS,FWHT] and Leg2[NRGY,NGAS,GASP] recorded as Leg1[AGRI,GROS,**GASP**] and Leg2 [NRGY, NGAS,**FWHT**].

**Comment by kristinehui** [comment]
Fixed
