### ISSUE TITLE
Portfolio Swap Product Definitions

### ISSUE THREAD

**Issue by TonyBirrell** [ANNA-DSB/Product-Definitions#128]
Amendments to the templates include:

- New Index enumeration list
- List to include value of 'Other' & 'Custom Prop Index'
- 'Custom Prop Index' allows user input to be validated against previously submitted prop indices
- Underlying Instrument ISIN as user input
- Allow a single value in Underlying fields within a portfolio swap

**Comment by kristinehui** [comment]
Amended
