### ISSUE TITLE
Expiry date not relevant for Equity swap CFDs

### ISSUE THREAD

**Issue by AndreasEngvallSEB** [ANNA-DSB/Product-Definitions#132]
Equity CFDs do not have a maturity date and the date has been removed according to issue #41 and in issue #63 the recommendation was to set Expiry date to 9999-12-31. 
In the current UAT templates (1.3) Annex 4 (September), Equity swaps with CFD as Return or Payout Trigger require Expiry date. Will submitting 9999-12-31 work for these instruments or what do you suggest?

**Comment by TonyBirrell** [comment]
Hi Andreas
Could you please direct your query to secretariat@anna-dsb.com
Thanks
