### ISSUE TITLE
use of JSON Schema primitive types

### ISSUE THREAD

**Issue by rawmatt** [ANNA-DSB/Product-Definitions#136]
For fields that are inherently boolean, such as $.properties.Derived.properties.CommodityDerivativeIndicator.type in https://github.com/ANNA-DSB/Product-Definitions/blob/master/PROD/JSON/Credit/Credit.Swap.ABS.InstRefDataReporting.V1.json, why are they of type "string" and not "boolean". Please help me understand the design decision.

**Comment by rawmatt** [comment]
Add .type on the JSONPath.

**Comment by TonyBirrell** [comment]
Hi, Could you please send an email to secretariat@anna-dsb.com
