### ISSUE TITLE
ANNA schema should not allow empty arrays or empty array elements

### ISSUE THREAD

**Issue by johnpaulwilkinson** [ANNA-DSB/Product-Definitions#144]
As per the new ANNA schema, some products can have UnderlyingInstrumentIndex as [], and UnderlyingInstrumentISIN array can have "". This should not be permitted by the schema as it means we will have to perform custom processing of client requests to remove these elements e.g. 

{
  "products": [
    {
      "Attributes": {
        "DeliveryType": "CASH",
        "ExpiryDate": "2017-11-03",
        "NotionalCurrency": "AED",
        "PriceMultiplier": 1,
        "ReturnorPayoutTrigger": "Forward price of underlying instrument",
        "Underlying": {
          "UnderlyingInstrumentISIN": ["GB0000055888"],
          "UnderlyingInstrumentIndex": []
        }
      }
    },
    {
      "Attributes": {
        "DeliveryType": "CASH",
        "ExpiryDate": "2017-11-03",
        "NotionalCurrency": "AED",
        "PriceMultiplier": 1,
        "ReturnorPayoutTrigger": "Forward price of underlying instrument",
        "Underlying": {
          "UnderlyingInstrumentISIN": ["GB0000055888",""],
        }
      }
    }
  ]
}

**Comment by TonyBirrell** [comment]
Hi
Please submit your query to secretariat@anna-dsb.com
