### ISSUE TITLE
Credit.Swap.Index has DebtSeniority as required but its enum values are blank

### ISSUE THREAD

**Issue by aaoferreira** [ANNA-DSB/Product-Definitions#146]
Unlinke other `DebtSeniority` values, the one listed as required on `Credit.Swap.Index` has an "empty" enum values list and consequently fails the record requests.

https://github.com/ANNA-DSB/Product-Definitions/blob/master/UAT/JSON/Credit/Request.Credit.Swap.Index.InstRefDataReporting.json#L768

**Comment by aaoferreira** [comment]
The same for `Credit.Swap.Index_Tranche`

**Comment by TonyBirrell** [comment]
Hi,
Please submit your query to secertariat@anna-dsb.com
