### ISSUE TITLE
Commodity Basis normalisation for non-standard products - Additional Sub Product might not be swapped

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#155]
**Problem:**
 For commodity basis underling in non-standard products:
Only if BaseProduct/Sub Product is the same as Other BaseProduct/Sub Product, and Additional Sub Product is second alphabetically and Other Additional Sub Product is first alphabetically, the swapping of Additional Sub Product does not happen.

**Impact:** 
3  templates
•	Other.Option.Non_Standard
•	Other.Swap.Non_Standard
•	Other.Other.Non_Standard

**Environment:**
UAT

**Comment by NathanDagg** [comment]
Released 17th February.
