### ISSUE TITLE
Commodity Basis normalisation for non-standard products – Reference Rate Commodities and Other Reference Rate Commodities might be swapped independently of Base Product/Sub Product/Additional Sub Product

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#156]
Reference Rate Commodities and Other Reference Rate Commodities should be swapped if Other Reference Rate Commodities is first alphabetically and Reference Rate Commodities is second alphabetically provided Base Product/Sub Product/Additional Sub Product are the same as Other Base Product/Sub Product/Additional Sub Product. 

**Impact:**
3 templates
• Other.Option.Non_Standard
• Other.Swap.Non_Standard
• Other.Other.Non_Standard
**Environment:**
UAT

**Comment by NathanDagg** [comment]
Released 17th February.
