### ISSUE TITLE
Equity Swaps - Total Return Swaps please add to DSB UAT Product Definitions Annex 4 - Equity

### ISSUE THREAD

**Issue by AlanClarkInvestec** [ANNA-DSB/Product-Definitions#157]
In the DSB Annex 4 you omitted to detail  Total Return Swaps  - please add

**Comment by AlanClarkInvestec** [comment]
@TonyBirrell FYI I have raised this documentation issue which may be of interest to you

**Comment by NataliaKozlovich** [comment]
Please submit your query to secretariat@anna-dsb.com
