### ISSUE TITLE
Product Definition - Annex4 Equity - Option Single_Name Product Definition Input

### ISSUE THREAD

**Issue by AlanClarkInvestec** [ANNA-DSB/Product-Definitions#158]
Product Definition Input
Notional Currency - please clarify what this is - should it read Strike Currency 
Also somewhat suprised Strike Price is not a Product Definition Input for Equity - Options ... lookig at ICE listed options they have different ISINs for Different Strike prices

**Comment by AlanClarkInvestec** [comment]
@TonyBirrell FYI I have raised this documentation issue which may be of interest to you

**Comment by NataliaKozlovich** [comment]
Please submit your query to secretariat@anna-dsb.com
