### ISSUE TITLE
Foreign_Exchange.Swap.FX_Swap does not work with Foreign_Exchange.Forward.Non_Standard

### ISSUE THREAD

**Issue by FilipVikstroem** [ANNA-DSB/Product-Definitions#159]
When making a request for a Fx Swap ISIN with Forward.Non_Standard ISINs you get the message

"Given ISIN/s must be an existing Foreign_Exchange.Forward.Forward product"

This means that you can't request ISIN for swaps in offshore yuan(CNH) where you need to use the Non_Standard template.

**Comment by NataliaKozlovich** [comment]
Please submit your query to secretariat@anna-dsb.com
