### ISSUE TITLE
Commodity names? bug

### ISSUE THREAD

**Issue by screig** [ANNA-DSB/Product-Definitions#161]
Is this correct? Having the comma inside 

            "CRUDE PALM OIL - MDEX,",
            "DAIRY - MILK - NZX,",
            "ELECTRICITY - APX - POWER INDEX: HOURLY,",
            "ELECTRICITY - POWER INDEX - HOURLY - GME,",
            "GAS OIL-0.5 SINGAPORE-PLATTS ASIA-PACIFIC,",
            "GASOLINE-WATERBORNE SPOT TOKYO BAY-RIM INTELLIGENCE PRODUCTS,",
            "Low Density Polyethylene General Purpose - Platts Polymerscan,",
            "Polypropylene Homopolymer Injection - Platts Polymerscan,",

**Comment by NathanDagg** [comment]
Hi, please send your query to secretariat@anna-dsb.com.
