### ISSUE TITLE
Enumeration of nothing

### ISSUE THREAD

**Issue by screig** [ANNA-DSB/Product-Definitions#162]
Here the first enumeration is blank, can this be changed to NA or something similar?

        "DebtSeniority": {
          "title": "Debt Seniority",
          "description": "Indicates the seniority of the debt, or debt basket or index underlying a derivative",
          "type": "string",
          "enum": [
            "",
            "SNDB",
            "MZZD",
            "SBOD",
            "JUND"
          ],
          "elaboration": {
            "": "n/a",
            "SNDB": "Senior Debt",
            "MZZD": "Mezzanine",
            "SBOD": "Subordinated Debt",
            "JUND": "Junior Debt"
          },
          "options": {
            "enum_titles": [
              "n/a",
              "Senior Debt",
              "Mezzanine",
              "Subordinated Debt",
              "Junior Debt"
            ]
          }

**Comment by NathanDagg** [comment]
Hi, please send your query to secretariat@anna-dsb.com.
