### ISSUE TITLE
Arrays needed?

### ISSUE THREAD

**Issue by screig** [ANNA-DSB/Product-Definitions#163]
This part of the defn below is causing me some confusion. The json says we need one of the three sub items, however for each sub item it is asking in each case for an array

                  "minItems": 1,
                  "maxItems": 1,

of length 1. So why use arrays at all here? 

File 
Equity.Forward.Price_Return_Basic_Performance_Single_Index.InstRefDataReporting.json

          "Underlying": {
          "minProperties": 1,
          "type": "object",
          "oneOf": [
            {
              "type": "object",
              "title": "UnderlyingInstrumentIndex",
              "properties": {
                "UnderlyingInstrumentIndex": {
                  "type": "array",
                  "uniqueItems": true,
                  "minItems": 1,
                  "maxItems": 1,
                  "items": {
                    "title": "Instrument Index",
                    "description": "Name of the index on which the financial instrument is based",
                    "type": "string",
                    "enum": [
                      "35X3I",
                       ***************Omitted for brevity*********************************
                      "WIG20": "WIG20"
                    }
                  }
                }
              },
              "required": [
                "UnderlyingInstrumentIndex"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "title": "UnderlyingInstrumentIndexProp",
              "properties": {
                "UnderlyingInstrumentIndexProp": {
                  "title": "Underlying Instrument Index Prop",
                  "type": "array",
                  "uniqueItems": true,
                  "minItems": 1,
                  "maxItems": 1,
                  "items": {
                    "title": "Underlying Instrument Index Prop",
                    "description": "Underlying Instrument Index Prop",
                    "type": "string"
                  }
                }
              },
              "required": [
                "UnderlyingInstrumentIndexProp"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "title": "UnderlyingInstrumentISIN",
              "properties": {
                "UnderlyingInstrumentISIN": {
                  "title": "Underlying Instrument ISIN",
                  "type": "array",
                  "uniqueItems": true,
                  "minItems": 1,
                  "maxItems": 1,
                  "items": {
                    "title": "Underlying Instrument ISIN",
                    "description": "Underlying Instrument Index ISIN",
                    "type": "string",
                    "pattern": "^$|^[A-Z]{2}[A-Z0-9]{9}[0-9]$"
                  }
                }
              },
              "required": [
                "UnderlyingInstrumentISIN"
              ],
              "additionalProperties": false
            }
          ]

**Comment by NathanDagg** [comment]
Hi, please send your query to secretariat@anna-dsb.com.
