### ISSUE TITLE
Bug in underlying class?

### ISSUE THREAD

**Issue by screig** [ANNA-DSB/Product-Definitions#164]
Is this correct

I can pass in an array of zero items?

File : Equity.Forward.Price_Return_Basic_Performance_Basket_CFD.InstRefDataReporting.V1.json

![captursfasfasfae](https://user-images.githubusercontent.com/4292074/38944808-5278ff20-4324-11e8-97f9-22092fea9911.PNG)

**Comment by NathanDagg** [comment]
Hi, please send your query to secretariat@anna-dsb.com.
