### ISSUE TITLE
Correction script for GitHub issue #149

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#167]
20 ISINs in UAT will be updated to correct data issue logged in GitHUb #149.
 
ISIN Status will be updated to Deleted, LastUpdateDateTime will be updated with the timestamp of the update, ISIN Status Reason will be prepended using “;” in the following format:
LastUpdateDateTime: Deleted due to missing normalization for negative values of ReferenceRateTerm/UnderlyingInstrumentIndexTerm. GitHub#;
Example: 2018-02-12T13:40:20: Deleted due to missing normalization for negative values of ReferenceRateTerm/UnderlyingInstrumentIndexTerm. GitHub #149;
 
**Environment:**
UAT

**Comment by NathanDagg** [comment]
UAT – May 27, 2018
