### ISSUE TITLE
Correction script for GitHub issue #151

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#168]
115 ISINs in UAT and  181 in Production will be updated to correct data issue logged in GitHub #151.

If ISIN Status <>Expired, ISIN Status will be updated to Updated, LastUpdateDateTime will be updated with the timestamp of the update, ISIN Status Reason will be prepended using “;” in the following format: 
LastUpdateDateTime:CFI Code corrected to have 'M' as third letter. GitHub#; 
Example: 2018-02-12T13:40:20: CFI Code corrected to have 'M' as third letter. GitHub #151;
If ISIN Status =Expired, ISIN Status remains Expired, LastUpdateDateTime updated with the timestamp of the update, ISIN Status Reason will be prepended as above.
 
**Environment:**
UAT, Production

**Comment by NathanDagg** [comment]
UAT – May 27, 2018
Production – June 17, 2018
