### ISSUE TITLE
Correction script for GitHub issue#152

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#169]
54675 ISINs in UAT and 39767 ISINs in Production will be updated to correct data issue logged in GitHub #152. 
If ISIN Status <>Expired, ISIN Status will be updated to Updated, LastUpdateDateTime will be updated with the timestamp of the update, ISIN Status Reason will be prepended using “;” in the following format: 
LastUpdateDateTime: Full Name changed to contain 'Multiple ISINs' instead of ISINs listed themselves. GitHub#; 
Example: 2018-02-12T13:40:20: Full Name changed to contain 'Multiple ISINs' instead of ISINs listed themselves. GitHub #152;
If ISIN Status =Expired, ISIN Status will remain Expired, LastUpdateDateTime will be updated with the timestamp of the update, ISIN Status Reason will be prepended as above.
 
**Environment:**
UAT, Production

**Comment by NathanDagg** [comment]
UAT – May 27, 2018
Production – June 17, 2018
