### ISSUE TITLE
New Reference Rate Enumeration - SOFR Compound

### ISSUE THREAD

**Issue by NathanDagg** [ANNA-DSB/Product-Definitions#170]
The DSB will be updating our enumeration list to accommodate the addition of Secured Overnight Financing Rate (SOFR).
The SOFR addition will mean a new value in the FpML (Financial products Markup Language) floating rate index schema, which the DSB currently uses to source its ‘Reference Rate’, ‘Other Reference Rate’ and ‘Underlying Instrument Index’ (CapFloor only) enumeration list for interest rate product definitions.

The International Swaps and Derivatives Association, Inc. (ISDA) has published the pre-publication draft for the USD-SOFR-COMPOUND floating rate index, with a tentative release date of 16th May 2018 (Note: this pre-publication draft can be subject to change).

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT

**Comment by NathanDagg** [comment]
Released to production on 20th May 2018.
