### ISSUE TITLE
Venezuelan Bolivar currency redenomination 

### ISSUE THREAD

**Issue by NathanDagg** [ANNA-DSB/Product-Definitions#172]
The Venezuelan government recently announced it will be redenominating their currency unit, the Bolivar, on 4th June 2018. 

The redenomination will mean a new currency code of ‘VES’ will be added to the ISO 4217 list, which the DSB currently uses to source ‘Notional Currency’, ‘Other Notional Currency’, ‘Settlement Currency’ and ‘Strike Price Currency’ enumeration lists

The DSB will be updating all impacted templates and will be releasing the FX asset class templates in UAT first, as this asset class is the most impacted based on the current count of ISINs created in production

**Comment by NathanDagg** [comment]
The redenomination will be postponed until further notice, as per the notification from the Venezuelan government.

**Comment by srwiltshire** [comment]
Delivered
