### ISSUE TITLE
Rates Inflation Basis Swaps

### ISSUE THREAD

**Issue by NathanDagg** [ANNA-DSB/Product-Definitions#176]
The Rates Inflation Basis Swap release into Production was planned for the 10th of June and would have incorporated the re-denominated Venezuelan Bolivar (ISO 4217 code: VES). 
Due to the uncertainty around the implementation of the re-denominated Venezuelan Bolivar, the implementation of the Rates Inflation Basis Swap template will have its Production release delayed by one week

Impact to users:
•	The current Rates Inflation Basis Swap in UAT has the ‘VES’ currency code as part of the ‘Notional Currency’ enumeration
•	The Rates Inflation Basis Swap templates will have the ‘VES’ code removed in UAT and a new template deployed on 6th June 2018
•	The updated template will promoted to Production on the 17th June 2018
•	Existing ISINs with VES currency created in UAT will not expire until the enumeration has been added back sometime in the future.

This template relates to #154

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed and validated in Production environment
