### ISSUE TITLE
Addition of new Floating Rate Index for Chilean Pesos (CLP-TNA) 

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#179]
The International Swaps and Derivatives Association, Inc. (ISDA) announced an update to the FpML floating rate scheme on 10th July 2018, resulting in an update of the relevant DSB enumeration. The DSB will be applying the usual business rules (see below) to allow for the publication of the " CLP-TNA " reference rate from July 6, 2018.

"CLP-TNA" - "Refers to the Indice Camara Promedio ("ICP") rate for Chilean Pesos which, for a Reset Date, is determined and published by the Asociacion de Bancos e Instituciones Financieras de Chile A.G. ("ABIF") in accordance with the "Reglamento Indice de Camara Promedio" of the ABIF as published in the Diario Oficial de la Republica de Chile (the "ICP Rules") and which is reported on the ABIF website by not later than 10:00 a.m., Santiago time, on that Reset Date." [For details, see Recommended EMTA-ISDA Market Practice - https://www.isda.org/a/JEoEE/SwapsCDsMP4.pdf]
Source: EMTA-ISDA

**Impact to users:**
•	Interest Rate products only 
o	The CLP-TNA addition will mean a new value in the FpML (Financial products Markup Language) floating rate index schema, which the DSB currently uses to source its ‘Reference Rate’, ‘Other Reference Rate’ and ‘Underlying Instrument Index’ (CapFloor only) enumeration list for interest rate product definitions
o	DSB Users will be able to create OTC ISINs with “CLP-TNA” rate for instruments with an expiry date of 6th July 2018 or later 
o	DSB Production: 28 templates will be updated
o	DSB UAT: 34 templates will be updated

**Comment by NathanDagg** [comment]
Deployed in PROD on 29th June 2018.
