### ISSUE TITLE
NEW TEMPLATE : FX Non-Deliverable Swap

### ISSUE THREAD

**Issue by srwiltshire** [ANNA-DSB/Product-Definitions#183]
A new template for FX Non-Deliverable Swap based on a pair of Non-Deliverable Forwards (NDFs) or FX Non-Standard Forwards.

**Comment by yurukov** [comment]
In the Sep announcement it was stated that:

> A new template will be introduced to support the creation of FX Swaps based on Non-Deliverable Forwards (including Off-Shore Currencies such as CNH).

Is this the template in question? I don't see CNH being allowed in the Non-Deliverable Forwards. Will F Swaps be allowed with Non-Standard Forwards or will CNH be added to Non-Deliverable Forwards? What's the ETA on this change?

**Comment by yurukov** [comment]
Soooo, my guess the announcement for CNH was not correct?

**Comment by NataliaKozlovich** [comment]
Please direct any product questions to DSB Secretariat <secretariat@ANNA-DSB.com>
