### ISSUE TITLE
Additional normalisations for Cross-Asset (Other) Non-Standard Swap, Cross-Asset (Other) Non-Standard Option and Cross-Asset (Other) Non-Standard Other

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#187]
New normalisations and validations specifically pertaining to instances where products have multiple attributes across each leg will be added.
Updated documentation explaining all the validations and normalisations for Cross-Asset templates is available https://www.anna-dsb.com/download/dsb-uat-product-definitions-annex-6-non-std/. 
Please refer to the new sections added to the document:
•	Combined Normalisation of Reference Rate and Commodity components (3.2.6)
•	Combined Normalisation of Cross Currency, Reference Rate and Commodity components (3.2.7)
•	Combined Normalisation of Cross Currency and Commodity components (3.2.8)
•	Combined Normalisation of Cross Currency, Optionality and Commodity components (3.2.9)
•	Combined Normalisation of Cross Currency, Optionality and Reference Rate components (3.2.10)
•	Combined Normalisation of Cross Currency, Optionality, Reference Rate and Commodity components (3.2.11)

**Comment by NathanDagg** [comment]
Released 17th February.
