### ISSUE TITLE
Delivery Type values correction for a Cross-Asset Swap 

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#188]
Following CFI Taxonomy, Delivery Type values for a Cross-Asset Swap: 
C	Cash
P	Physical
In order to provide a correct derivation of the CFI code for Other.Swap, ‘E- Elect at Settlement’ and ‘A-Auction’ values need to be removed from the Delivery Type enumeration list for Other.Swap.
No changes of Delivery Type are required for Cross-Asset Option or Cross-Asset Other.

**Comment by NathanDagg** [comment]
Released 17th February.
