### ISSUE TITLE
Additional validation for Base Product in Cross-Asset templates

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#189]
For templates:
- Other. Swap
- Other.Option
- Other.Other
If Base Product is included in the request, at least one of the following must be provided:
• Underlying Instrument Index (“OTHER” for Commodities)
• Commodities or Cross-Asset Proprietary Index (single or multiple)
• Commodities Reference Rate (single or multiple)

**Comment by NathanDagg** [comment]
Released 17th February.
