### ISSUE TITLE
RATES : Various : Add IR Term of Contract (Field 41) to Templates

### ISSUE THREAD

**Issue by srwiltshire** [ANNA-DSB/Product-Definitions#190]
ESMA has provided guidance that it is necessary to include the IR Term of Contract (Field 41) in the definition of RATES products. This field should contain the duration of the product from Effective Date to Unadjusted Expiry Date. It will require the addition of two new fields to the in scope templates:

TERM OF CONTACT VALUE (Integer < 999)

TERM OF CONTRACT UNIT (YEAR, MNTH, WEEK, DAYS)

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT on 6th July 2019.

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in Production on 22nd September 2019.
