### ISSUE TITLE
EQUTY : Portfolio Swap : Address need to support Single Stock and Single Index Portfolio Swaps

### ISSUE THREAD

**Issue by srwiltshire** [ANNA-DSB/Product-Definitions#191]
A request has been received from JPM to extend the support for Equity Portfolio Swaps to cover those instruments that have a Single Stock or a Single Index as an Underlier.At present, the Portfolio Swap template determines that are instruments created with that template have a Basket as an underlier and this is reflected in the CFI#3 (underlying asset) which is always set to B=Basket.The request proposes the creation of a set of templates:1. Portfolio_Swap_Single_Name2. Portfolio_Swap_Single_Index3. Portfolio_Swap_Basket4. Portfolio_Swap_Other...that would replace the existing Portfolio Swap template.

In order to proceed with this, it will be necessary to get answers from ESMA to the following questions:a. Can Portfolio Swaps support Single Name and Single Index underlying instrumentsb. What Portfolio Swaps would result in an Underlying Asset of Other?c. Is it still possible to create a Basket Portfolio Swap based on a Single Stock or Single Index?

Once these questions have been answered and the go ahead for the above plan is given, the existing Portfolio Swap will be renamed Portfolio_Swap_Basket and two (or three) new templates will need to be created to support the other underlying assets.

To progress this with the PC we need to obtain some basic statistics about numbers created and number of creators.

**Comment by NathanDagg** [comment]
Released 17th February.
