### ISSUE TITLE
Rates Inflation Basis Swap: DeliveryType and PriceMultiplier will be changed to optional

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#192]
In Rates.Swap.Inflation_Basis the following attributes has default values but are declared as required fields:
- DeliveryType
- PriceMultiplier
The fields will be changed to be optional.

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in Production on 22nd September 2019.
