### ISSUE TITLE
CNH with Swaps

### ISSUE THREAD

**Issue by yurukov** [ANNA-DSB/Product-Definitions#193]
In the Sep announcement it was stated that CNH will be added to the Swap product or a new non-standard product would be delivered that would allow creating swaps with non-standard forwards. This has not happened. 

Was there an announcement that the plan was scrapped? 
Is there an ETA on when will it be added?
This was raised with issue #159 back in May, but with no result.

**Comment by NathanDagg** [comment]
Please email queries to secretariat@anna-dsb.com

Thanks.
