### ISSUE TITLE
Cross-asset templates: Add IR Term of Contract (Field 41) when a rates component is included

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#194]

**Comment by NataliaKozlovich** [comment]
ESMA has provided guidance that it is necessary to include the IR Term of Contract (Field 41) in the definition of RATES products. This field should contain the duration of the product from Effective Date to Unadjusted Expiry Date. It will require the addition of two new fields to the cross-asset templates:

- TERM OF CONTACT VALUE (Integer < 999)
- TERM OF CONTRACT UNIT (YEAR, MNTH, WEEK, DAYS)

The two new attributes will be added to the Cross-Asset product templates to be used when a rates component is included

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT on 6th July 2019.

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in Production on 22nd September 2019.
