### ISSUE TITLE
FOREX : Non-Standard Forward : Allow two identical ccy codes if Place of Settlement is entered

### ISSUE THREAD

**Issue by srwiltshire** [ANNA-DSB/Product-Definitions#198]
At the moment it is not possible to enter a FX Non-Standard Forward that supports an exchange between the onshore and offshore versions of a currency (for example: CNY to CNH).By way of background it is not possible to allow the entry of the offshore currency code of CNH since it is not part of the ISO standard. For this reason, the user would need to enter a currency of CNY with a Settlement Ccy (eg: USD) and a Place of Settlement (eg: Hong Kong).

In order to support this functionality, it is necessary to allow the entry of two identical currency codes if, and only if, a Settlement Ccy and Place of Settlement is also present in the request.

**Comment by AnnaDSBTechnicalSupport** [comment]
Reopening this issue as the bug has been reintroduced in UAT only via the Field 41 release last July 6th.   
https://www.anna-dsb.com/download/2019-07-06-reminder-notification-ir-term-of-contract-rts-23-field-41-additional-rates-derivatives-enhancements-uat-prod/

Production is NOT impacted

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT on 20th July 2019.
