### ISSUE TITLE
RATES : Inflation Basis YoY : Create a new template

### ISSUE THREAD

**Issue by srwiltshire** [ANNA-DSB/Product-Definitions#204]
A new template is required to support an Inflation Basis YoY swap within the Rates asset class. This has been proposed by ISDA in order to bring the DSB templates into line with their taxonomy.
The template will be based on the Inflation Basis Zero Coupon template - accepting the same values (including underlying reference rates) and deriving the same CFI code. 
This is to be included in Q4 2019 release.

**Comment by NathanDagg** [comment]
Release into production.
