### ISSUE TITLE
RATES : New Reference Rate: GBP SONIA COMPOUNDED INDEX

### ISSUE THREAD

**Issue by srwiltshire** [ANNA-DSB/Product-Definitions#232]
A new Reference Rate is to be added to all Rates templates and Cross-Asset templates with a Floating Rate for SONIA Compound Index.

Name: GBP-SONIA-COMPOUNDED-INDEX
ISO: SONA

**Comment by AnnaDSBTechnicalSupport** [comment]
Deployed in UAT on 8/Aug/20.

**Comment by acgrace** [comment]
TO BE REMOVED - No FpML release confirmation received.

All the ISIN’s created using this enumeration will be removed.

**Comment by AnnaDSBTechnicalSupport** [comment]
[List of deleted ISINs in UAT created using enumaration SONIA COMPOUNDED INDEX .pdf](https://github.com/ANNA-DSB/Product-Definitions/files/6138466/List.of.deleted.ISINs.in.UAT.created.using.enumaration.SONIA.COMPOUNDED.INDEX.pdf)
