### ISSUE TITLE
Missing ANNA DSB product Definition Name

### ISSUE THREAD

**Issue by VivekJaiswalMarkit** [ANNA-DSB/Product-Definitions#28]
Below is the list of Indices for which DSB Product Definition Name are missing.

Could you please add them in use case or Underlying Instrument Index , so we can create the product ISIN for these indices as well.

[Missing ANNA DSB Product defintions.xlsx](https://github.com/ANNA-DSB/Product-Definitions/files/1044254/Missing.ANNA.DSB.Product.defintions.xlsx)

**Comment by TonyBirrell** [comment]
Hi Vivek
Thank you for your engagement.
Could you please send an email to the Secretariat to raise this issue formally:
secretariat@anna-dsb.com

Thanks
Tony
ANNA DSB Secretariat
