### ISSUE TITLE
DSB-2619 Commodities : Reference Price Update (Agriculture)

### ISSUE THREAD

**Issue by anjdelapena** [ANNA-DSB/Product-Definitions#312]
Issue:
ISDA is organizing a project to review and update Sub-Annex A, which has not been updated since its original publication in 2005. Sub-Annex A is comprised of the list of Commodities Reference Price (CRP) that entities can reference their OTC contracts.

Impact:
In line with this, ISDA has distributed a publication to advise an updated list of Commodities Reference Price in Agricultural products. This update is the initial phase as they will be reviewing the rest of the products as well.

The DSB is obliged to ensure that the enumeration list is up to date with the latest values from FpML commodityReferencePriceScheme and so it is necessary to add these new values in the list. The existing Commodities Ref Price in the DSB will not be removed or amended.

Workaround:
DSB will update its existing enumerated list to keep in line with the FpML publication.

**Comment by msurop** [comment]
This is already deployed in Production.
