### ISSUE TITLE
Attributes names to change in JSON templates to match the labels in the product definitions

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#50]
||Old Attribute Name||	New Attribute Name||
|LongName	|FullName|
|CFI	|ClassificationType|
|CommoditiesDerivativesIndicator	|CommodityDerivativeIndicator|
|Issuer|	IssuerorOperatoroftheTradingVenueIdentifier|
|FISN	|ShortName|
|ISOFirstLegReferenceRate	|ISOReferenceRate|
|ReturnPayout	|ReturnorPayoutTrigger|
|FirstLegReferenceRate	|ReferenceRate|
|ExerciseStyle	|OptionExerciseStyle|
|ValuationMethod|	ValuationMethodorTrigger|
|UnderlyingInstrumentCode	|UnderlyingInstrumentISIN|
|IssuerType	|UnderlyingIssuerType|
|UnderlyingIssuer	|UnderlyingInstrumentLEI|
|ISOUnderlyingInstrumentReferenceRate	|ISOUnderlyingInstrumentIndex|
|UnderlyingIndexName	|UnderlyingInstrumentIndex|
|IndexSeries	|UnderlyingCreditIndexSeries|
|IndexVersion	|UnderlyingCreditIndexVersion|
|FxType	|FXType|
|OtherLegNotionalCurrency	|OtherNotionalCurrency|
|FirstLegReferenceRateTermValue	|ReferenceRateTermValue|
|FirstLegReferenceRateTermUnit	|ReferenceRateTermUnit|
|SingleOrMultiCurrency	|SingleorMultiCurrency|
|UnderlyingIsinOrLei	|UnderlyingInstrumentISINorLEI|
|UnderlyingInstrumentReferenceRates|UnderlyingInstrumentIndex|
|UnderlyingInstrumentCodes|UnderlyingInstrumentISIN|

**Comment by taynes13** [comment]
I see in review comments that UnderlyingIssuer was renamed to UnderlyingInstrumentLEI, but I see in the actual change set that it was sometimes renamed to UnderlyingInstrumentLEI and sometimes to UnderlyingIssuerType. Is this by mistake? Which names are correct?

**Comment by NataliaKozlovich** [comment]
Please forward your enquiry to technical.support@ANNA-DSB.com
