### ISSUE TITLE
Incorrect ISOUnderlyingInstrumentIndex getting derived for all Product "Index"

### ISSUE THREAD

**Issue by VivekJaiswalMarkit** [ANNA-DSB/Product-Definitions#51]
Whenever we are creating ISIN for product "Index" using any of the Underlying Instrument Index, we are getting derived "ISOUnderlyingInstrumentIndex" as iTraxxEurope. 

For e.g., when we select the Underlying Instrument Index as "CDXIG" under attributes, the derived ISO Underlying Instrument Index is getting generated as iTraxxEurope. 

{"Header":{"AssetClass":"Credit","InstrumentType":"Swap","UseCase":"Index","Level":"InstRefDataReporting"},"Attributes":{"ExpiryDate":"2022-03-20","UnderlyingInstrumentIndex":"CDXIG","UnderlyingInstrumentIndexTermUnit":"YEAR","UnderlyingInstrumentIndexTermValue":5,"DebtSeniority":"SNDB","UnderlyingCreditIndexSeries":28,"UnderlyingCreditIndexVersion":1},"ISIN":{"ISIN":"EZ1MT2VWVH68","Status":"New"},"TemplateVersion":1,"Derived":{"ISOUnderlyingInstrumentIndex":"iTraxxEurope","CommodityDerivativeIndicator":"FALSE","NotionalCurrency":"EUR","IssuerorOperatoroftheTradingVenueIdentifier":"NA","UnderlyingAssetType":"Index","ReturnorPayoutTrigger":"Credit Default","UnderlyingIssuerType":"Corporate","DeliveryType":"OPTL","PriceMultiplier":1,"FullName":"Credit Swap Index CDXIG EUR 20220320","ShortName":"NA/CDS Corp Idx Sr EUR 20220320","ClassificationType":"SCICCA"}}

**Comment by NataliaKozlovich** [comment]
Please forward your enquiry to technical.support@ANNA-DSB.com
