### ISSUE TITLE
When UnderlyingInstrumentIndex is iTraxxSovX then UnderlyingIssuerType should be Sovereign 

### ISSUE THREAD

**Issue by VivekJaiswalMarkit** [ANNA-DSB/Product-Definitions#52]
Currently whenever ISIN is created for Index when UnderlyingInstrumentIndex is "iTraxxSovX" the derived UnderlyingIssuerType is getting created as "Corporate".

However ideally it should be Sovereign, as all the constituents in this index are Sovereign Entities.

**Comment by NataliaKozlovich** [comment]
Please forward your enquiry to technical.support@ANNA-DSB.com
