### ISSUE TITLE
Missing indices for ISIN creation

### ISSUE THREAD

**Issue by VivekJaiswalMarkit** [ANNA-DSB/Product-Definitions#53]
There is an issue with the creation of ISIN for iTraxxSovX, Currently there are list of SovX indices which have different Series and Versions as shown below.

iTraxx SovX Asia Pacific Series 10 Version 1
iTraxx SovX Asia Pacific Series 3 Version 1
iTraxx SovX Asia Pacific Series 4 Version 1
iTraxx SovX Asia Pacific Series 5 Version 1
iTraxx SovX Asia Pacific Series 6 Version 1
iTraxx SovX Asia Pacific Series 7 Version 1
iTraxx SovX Asia Pacific Series 8 Version 1
iTraxx SovX Asia Pacific Series 9 Version 1
iTraxx SovX BRIC Series 10 Version 1
iTraxx SovX BRIC Series 11 Version 1
iTraxx SovX BRIC Series 12 Version 1
iTraxx SovX BRIC Series 13 Version 1
iTraxx SovX BRIC Series 14 Version 1
iTraxx SovX BRIC Series 3 Version 1
iTraxx SovX BRIC Series 4 Version 1
iTraxx SovX BRIC Series 5 Version 1
iTraxx SovX BRIC Series 6 Version 1
iTraxx SovX BRIC Series 7 Version 1
iTraxx SovX BRIC Series 8 Version 1
iTraxx SovX BRIC Series 9 Version 1
iTraxx SovX CEEMEA ex-EU Series 10 Version 2
iTraxx SovX CEEMEA ex-EU Series 11 Version 2
iTraxx SovX CEEMEA ex-EU Series 12 Version 2
iTraxx SovX CEEMEA ex-EU Series 13 Version 2
iTraxx SovX CEEMEA ex-EU Series 14 Version 2
iTraxx SovX CEEMEA ex-EU Series 8 Version 2
iTraxx SovX CEEMEA ex-EU Series 9 Version 2
iTraxx SovX CEEMEA Series 1 Version 2
iTraxx SovX CEEMEA Series 10 Version 2
iTraxx SovX CEEMEA Series 11 Version 2
iTraxx SovX CEEMEA Series 2 Version 2
iTraxx SovX CEEMEA Series 3 Version 2
iTraxx SovX CEEMEA Series 4 Version 2
iTraxx SovX CEEMEA Series 5 Version 2
iTraxx SovX CEEMEA Series 6 Version 2
iTraxx SovX CEEMEA Series 7 Version 2
iTraxx SovX CEEMEA Series 8 Version 2
iTraxx SovX CEEMEA Series 9 Version 2
iTraxx SovX G7 Series 1 Version 1
iTraxx SovX G7 Series 10 Version 1
iTraxx SovX G7 Series 11 Version 1
iTraxx SovX G7 Series 12 Version 1
iTraxx SovX G7 Series 13 Version 1
iTraxx SovX G7 Series 14 Version 1
iTraxx SovX G7 Series 2 Version 1
iTraxx SovX G7 Series 3 Version 1
iTraxx SovX G7 Series 4 Version 1
iTraxx SovX G7 Series 5 Version 1
iTraxx SovX G7 Series 6 Version 1
iTraxx SovX G7 Series 7 Version 1
iTraxx SovX G7 Series 8 Version 1
iTraxx SovX G7 Series 9 Version 1
iTraxx SovX Global Liquid Investment Grade Series 1 Version 2
iTraxx SovX Global Liquid Investment Grade Series 10 Version 1
iTraxx SovX Global Liquid Investment Grade Series 11 Version 1
iTraxx SovX Global Liquid Investment Grade Series 12 Version 1
iTraxx SovX Global Liquid Investment Grade Series 13 Version 1
iTraxx SovX Global Liquid Investment Grade Series 14 Version 1
iTraxx SovX Global Liquid Investment Grade Series 2 Version 2
iTraxx SovX Global Liquid Investment Grade Series 3 Version 2
iTraxx SovX Global Liquid Investment Grade Series 4 Version 1
iTraxx SovX Global Liquid Investment Grade Series 5 Version 1
iTraxx SovX Global Liquid Investment Grade Series 6 Version 1
iTraxx SovX Global Liquid Investment Grade Series 7 Version 1
iTraxx SovX Global Liquid Investment Grade Series 8 Version 1
iTraxx SovX Global Liquid Investment Grade Series 9 Version 1
iTraxx SovX Latin America Series 10 Version 2
iTraxx SovX Latin America Series 11 Version 2
iTraxx SovX Latin America Series 12 Version 1
iTraxx SovX Latin America Series 13 Version 1
iTraxx SovX Latin America Series 14 Version 1
iTraxx SovX Latin America Series 5 Version 2
iTraxx SovX Latin America Series 6 Version 2
iTraxx SovX Latin America Series 7 Version 2
iTraxx SovX Latin America Series 8 Version 2
iTraxx SovX Latin America Series 9 Version 2
iTraxx SovX Western Europe Series 1 Version 2
iTraxx SovX Western Europe Series 2 Version 2
iTraxx SovX Western Europe Series 3 Version 2
iTraxx SovX Western Europe Series 4 Version 2
iTraxx SovX Western Europe Series 5 Version 2
iTraxx SovX Western Europe Series 6 Version 2
iTraxx SovX Western Europe Series 7 Version 1
iTraxx SovX Western Europe Series 8 Version 1

However we have only option to create the ISIN with iTraxx SovX. So not clear which value needs to be picked for series and value while ISIN creation. 

This issue is with across all indices where only index family is mentioned by main indices are missing.

**Comment by NataliaKozlovich** [comment]
Please forward your enquiry to technical.support@ANNA-DSB.com
