### ISSUE TITLE
Debt Seniority is not relevant for Credit Index underliers

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#58]
Default "Debt Seniority" to "n/a" for index underliers and do not return as part of the ISIN record for these products

**Comment by VivekJaiswalMarkit** [comment]
Need Clarification, will this field be removed from schema or only he underlining value will be changed to n/a.

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
