### ISSUE TITLE
Underlying Asset Type for Credit Total Return Swap

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#59]
TRS Products can have a Single Name or Index underlying. Amend functionality in TRS definition to provide Underlying Instrument ISIN or Underlying Instrument Index + Underlying Credit Index Series & Version + ISO Underlying Instrument Index but not both

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
