### ISSUE TITLE
Underlying Instrument ISIN to be substituted for Underlying Index Name for Equities Index Underliers

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#60]
Not all Equity Indexes have ISINs. Substitute Underlying Instrument ISIN for Underlying Index Name, DSB to utilise a mapping service to provide an ISIN if it exists

**Comment by YuvalCohen** [comment]
This has not yet been finalised;
The DSB are engaging with ANNA to determine requirements.

**Comment by YuvalCohen** [comment]
Users should always send the index name.
Current implementation is correct where users cannot send the index ISIN.
