### ISSUE TITLE
Valuation method or Trigger for FX NDO

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#61]
Amend enumerations for Valuation method or Trigger for FX NDO to include every CFI char#5 code apart from Digital and Barrier.

**Comment by nehamittal8** [comment]
Hi. I don't see any change in the enumerations for Valuation Method or Trigger from last release. Can you please clarify?

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
