### ISSUE TITLE
FX Options normalisation

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#64]
Validation required to associate a EUR put with a USD call for example.
New list of currencies "Ccy Quote Convention" to be adopted in the order provided for validation purposes only. Notional Currency is always related to the Option Type. Reorder the currencies input per the currency list so that there is a standard convention - the currency that appears first in the list becomes Notional currency. Once ordered if this matches the user request then no change, if not the Option Type will be flipped.

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
