### ISSUE TITLE
Commodities Multi Exotic templates

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#68]
1) Add 'Underlying Instrument Index' into the product definitions for Multi exotic Swap, Option & Forward
2) Make Reference rate mandatory & Underlying instrument Index optional for all multi-exotic templates. Both fields can accept multiple values and are enumerated lists
3) Add as a derived field "ISO Underlying Instrument Index" - if more than one index input into 'Underlying Instrument Index' then derive 'Multiple Indices' if only one then truncate to 25 characters and return the name

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
