### ISSUE TITLE
Underlying Issuer Type for Credit Index

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#70]
User raised an issue that When UnderlyingInstrumentIndex is "iTraxxSovX", the derived UnderlyingIssuerType is"Corporate", should be Sovereign.
"Underlying Issuer Type" for Credit Index and Index Tranche will be moved to User Input.
"Underlying Issuer Type" dropdown to have the following values: Corporate, Sovereign, Local. This is CFI char#5 for Credit Swaps.

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
