### ISSUE TITLE
ISOUnderlyingInstrumentIndex for Credit Index and Index Tranche 

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#71]
Bug fix: For Credit Index and Index Tranche products, ISOUnderlyingInstrumentIndex was incorrectly derived as ‘iTraxx Europe’ / ‘iTraxx Europe Tranche’ at all times. UnderlyingInstrumentIndex user input will be converted to the ISO format and returned as ISOUnderlyingInstrumentIndex.

**Comment by TonyBirrell** [comment]
Bug fix: Credit Index Tranche contains the incorrect enumerated Index List. This is being corrected

**Comment by wigbam** [comment]
Please also note that ISOUnderlyingInstrumentIndex has a typo in one of the enum entries: "StandardiTraxxEuropeTranc"

**Comment by TonyBirrell** [comment]
Hi Stepan,

This field is a truncated version of the Underlying Instrument Index field due to ESMA’s formatting requirements of Alphanumeric 25 characters.

Kind Regards,

Tony Birrell

City Tower
40 Basinghall St
London EC2V 5DE

tel:    020 3770 5817

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
