### ISSUE TITLE
Commodities Basis Definition Normalisation

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#73]
Within the Basis template, apply an alphabetic normalisation of Leg 1 (Base Product/Sub Product/Additional Sub Product/Reference Rate) and Leg 2 (Other Base Product/Other Sub Product/Other Additional Sub Product/Other Reference Rate).

If “Base Product” and “Other Base Product” are different – alphabetically order them. The Base Product should be the first alphabetically and Other Base Product the second alphabetically. 
Otherwise, if “Sub product” and “Other Sub product” are different – alphabetically order them. The Sub Product should be the first alphabetically and Other Sub Product the second alphabetically.
Otherwise, if “Additional Sub Product” and “Other Additional Sub product” are different – alphabetically order them. The Additional Sub Product should be the first alphabetically and Other Additional Sub Product the second alphabetically.
 If “Base Product/ Sub Product/ Additional Sub Product” and “Other Base Product/ Other Sub Product/ Other Additional Sub Product” are the same, alphabetically order Reference Rate and Other Reference Rate.

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
