### ISSUE TITLE
UnderlyingInstrumentISIN to have a type array

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#76]
UnderlyingInstrumentISIN will be an array. For products that can only hold one ISIN, JSON templates will be changed from
"UnderlyingInstrumentISIN":"EZ1234567882” to "UnderlyingInstrumentISIN":["EZ1234567882”].
For products that can hold multiple ISINs, JSON templates will remain: "UnderlyingInstrumentISIN":["EZ1234567882","EZ1234567890"]

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release

**Comment by andyjgordon** [comment]
The implementation of issue 67 - Equity Baskets means that you now no longer have any multiple ISIN products that use the UnderlyingInstrumentISIN field - they now are called Underlying...InstrumentISINs. So you now have an UnderlyingInstrumentISIN field for Equities that is an Array type but only ever holds a single item. 

So far i have managed to use the same type in our code for serialisation of all of the Product Definitions but the inconsistency of UnderlyingInstrumentISIN being an array for Equities means we will need to do some extra handling for this field - when it is not really needed. 

Could UnderlyingInstrumentISIN be changed back to a string type for Equities?

**Comment by TonyBirrell** [comment]
Hi, Please send your inquiry to secretariat@anna-dsb.com
