### ISSUE TITLE
ISIN Status and Reason

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#79]
For all products:
A new ISIN Status=Expired to be added.
A new attribute "ISIN Status Reason" to be added. 
The DSB will develop a daily process that will run over night and set ISIN Status to Expired for ISINs that have Expiry Date < Today.
ISIN Status can only be changed by the DSB. 
Any change to the ISIN Status will need to have a reason.

**Comment by BhuvaneshBabu** [comment]
Can you please provide all the possible enumerations for ISIN Status. 
Would there be a enumeration to determine at ISIN create request, if ANNA is creating a New ISIN or returning existing ISIN if already created.

**Comment by TonyBirrell** [comment]
Hi BhuvaneshBabu,
Please email your enquiry directly to the secretariat@ANNA-DSB.com
Thanks

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
