### ISSUE TITLE
Base Product, Sub Product and Additional Sub Product structure changes in JSON Request for Commodities

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#83]
Format in which Base Product, Sub Product and Additional Sub Product is stored in JSON requests for commodities changes as follows
"BaseProduct":{"NRGY": {" NGAS": {"AdditionalSubProduct":"GASP"}}},
Instead of:
"BaseProduct":{"Energy[NRGY]": {"NaturalGas[NGAS]": {"AdditionalSubProduct":"GasPool[GASP]"}}},

**Comment by pkotturi** [comment]
Please consider the above change for Other Base Product, Other Sub Product and Other Additional Sub Product as well. All 6 attributes should be in sync in both request and response JSON messages.

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
