### ISSUE TITLE
Other Sub Product, Other Base Product, Other Additional Sub Product FPML XPath Request for Commodities

### ISSUE THREAD

**Issue by souvikdeb** [ANNA-DSB/Product-Definitions#84]
Can ANNA share the XPATH for these new attributes? @NataliaKozlovich

**Comment by NataliaKozlovich** [comment]
Thank you for your enquiry. The DSB does not provide xpath for any of the products. If you have any further questions, please do get in touch with our Secretariat Team at secretariat@ANNA-DSB.com

**Comment by souvikdeb** [comment]
The attached document was a guideline provided earlier based on the attributes  being considered.  Will there be an updated guideline that will be published based on the additional attributes introduced.
[DSBPC-CP001-Consultation-Paper-Phase-1-FINAL_FIX_response.pdf](https://github.com/ANNA-DSB/Product-Definitions/files/1193494/DSBPC-CP001-Consultation-Paper-Phase-1-FINAL_FIX_response.pdf)
