### ISSUE TITLE
Question: mixed use of property name and value to identify sub product/additional product etc.

### ISSUE THREAD

**Issue by tongc** [ANNA-DSB/Product-Definitions#9]
e.g. in Request.Commodities.Swap.Commodities_Swap.InstRefDataReporting.json, inside Attributes.BaseProduct. 
we need to make a JSON request like 
<pre>
		"BaseProduct": {
			"Paper": {
				"Newsprint": {}
			}
		}
</pre>
where in response, the data structure is like the below
<pre>
                "BaseProduct": "culpa aliqua dolor",
		"AdditionalSubProduct": "amet magna ullamco et",
		"SubProduct": "aliquip officia exercitation"
</pre>
I wonder if there is any plan to change the request to have the same data structure as in the response. This flattened data structure is much easier to consume and transform and also more compatible with the PDF spec.

**Comment by YuvalCohen** [comment]
For such queries, please contact directly technical.support@anna-dsb.com
