### ISSUE TITLE
JSON files are not updates with Required attributes.

### ISSUE THREAD

**Issue by souvikdeb** [ANNA-DSB/Product-Definitions#90]
Please refer to screenshot attached.
![2](https://user-images.githubusercontent.com/28786221/29094038-dc838196-7c59-11e7-8c1b-e46015f2518d.png)

**Comment by TonyBirrell** [comment]
Thank you for your comment.
This is being addressed as part of Github #88

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
