### ISSUE TITLE
Fix for 4 Rates templates: enumeration value for UnderlyingAsseType attribute 

### ISSUE THREAD

**Issue by NataliaKozlovich** [ANNA-DSB/Product-Definitions#93]
The following JSON templates have "Basis swap (Float - Float)" value for UnderlyingAsseType. This will be amended to "Basis Swap (Float - Float)" to get all the templates in line:
Rates.Option.CapFloor.InstRefDataReporting.V1.json
Rates.Option.Debt_Option.InstRefDataReporting.V1.json
Rates.Option.Swaption.InstRefDataReporting.V1.json
Request.Rates.Option.Swaption.InstRefDataReporting.json

**Comment by TonyBirrell** [comment]
Implemented during the 28th August UAT release
