### ISSUE TITLE
FX Options notional & other currency need clarification

### ISSUE THREAD

**Issue by andreyutkin** [ANNA-DSB/Product-Definitions#95]
Hello team,

Looking at the latest docs (Aug release),

For all FX Option templates but NDO:

- Notional currency (interpreted as put currency) should match RTS 23 field 13
- Other notional currency (interpreted as call currency) should match RTS 23 field 47

1) For NDO there's no relation to put currency or call currency - why? Is it a typo?

2) RTS 23 field 13 means currency is which notional is denominated, field 47 means another currency of the pair (not the one reported in field 13). It is not related to call / put currency at all. Should we use it as guidance?

See also issue #64 - this is again a different approach, not sure what to follow

Appreciate the response!

**Comment by TonyBirrell** [comment]
Hi, could you please email the secretariat@ANNA-DSB.com directly
