### ISSUE TITLE
Single Index and Basket Equity Options

### ISSUE THREAD

**Issue by PeterDavisLGIM** [ANNA-DSB/Product-Definitions#96]
Why is it required to supply only the “Underlying Instrument Index” as an input field for the "OPTION - Single_Index" Product Definition but for the "OPTION - Basket" Product Definition the requirement is “Underlying instrument ISIN” & “Underlying Instrument Index”  (presumably as a list).  How should the list be delimited ?

**Comment by TonyBirrell** [comment]
Addressed through the secretariat - The Single Index by definition can only have one underlying value however a basket can be comprised of both underlying stocks and underlying indices hence the functionality to enter multiple values. The user input will be delimited by “;”
