### ISSUE TITLE
List of Underlying Indexes

### ISSUE THREAD

**Issue by PeterDavisLGIM** [ANNA-DSB/Product-Definitions#97]
In reference to the main "UAT Product Definitions" document.
Regarding Underlying Instrument Index.
Section 5 states that an annex will be published for the list of Credit/Equity/Commodity indexes.
Section 7 states for this field “Industry verified, list of global trademarked (where applicable) indices”

Has this list been published ? If so where is it located ?

**Comment by TonyBirrell** [comment]
Addressed through the secretariat - The equity list of indices exists in the JSON templates. The list is comprised of the global trademarked names of indices listed on G20 exchanges. This list is not final and hence has not been published, the DSB is in discussions with ESMA as to the level of granularity that is acceptable for MiFID II Reference Data Reporting.
